[package]
name = "not_xcopy"
version = "0.1.0"
authors = ["kotone-shiinoha <kotone.shiinoha@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]